### request varibaels define. // @name requestName or # @name requestName
### The request variable reference syntax follows 
### {{requestName.(response|request).(body|headers).(*|JSONPath|XPath|Header Name)}}.

@host=localhost:1080

### login request
# @name login
POST /login HTTP/1.1
Host: {{host}}
Content-Type: application/x-www-form-urlencoded

username=foo&password=bar
